### ISSUE TITLE
How is ReactInstance supposed to be used?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/fable-react#131]
I am using a property that needs a `ReactInstance`. My code, simplified, is (using Material-UI):

```f#
div [] [
  textField [] []
  popper [ AnchorEl (* what to put here to reference the text field above? *) ] []
]
```

where `MaterialProp.AnchorEl: ReactInstance -> MaterialProp`.

I see that `ReactInstance` is an alias for `U2<Component<obj, obj>, Element>`. But how can I get either a `Component` or `Element` for the type I need? I currently generate a random GUID-based ID in the component constructor and use

```f#
div [] [
  textField [ Id textFieldId ] []
  popper [ AnchorEl !^(Fable.Import.Browser.document.getElementById textFieldId) ] []
]
```

which works, but doesn't seem very "react-ish".

**Comment by alfonsogarciacaro** [comment]
Not sure if it's the "best" way to do it, but I cannot think of an alternative atm as I haven't tested the library :) I tend to trust more the official documentation than the bindings, because they may have errors or be outdate (in fact, I'm thinking of removing the Fable.Import.React file from the library) and the docs for material-ui `anchorEl` only talk about a DOM element.

You can add the ID to your model if you don't to generate a random one in the view function.

**Comment by cmeeren** [comment]
Thanks. Random IDs it is, then. :)
