### ISSUE TITLE
ReactElementType.create compiles but editor shows error

### ISSUE THREAD

**Issue by halcwb** [fable-compiler/fable-react#142]
When using ReactElementType.create, the editor (VSCode and VS) shows an error because it references the interface type not the module. Fable compiler can compile the code though. 

Is this specific to 4.1.3? I see that in later versions the namespacing has been changed.

**Comment by alfonsogarciacaro** [comment]
Hmm, the React helpers use `#if FABLE_COMPILER` for conditional compilation to support also SSR on .NET. It seems that we made a mistake in 4.1.3 and the .dll from the Nuget package doesn't include `ReactElementType.create`. That's why the editor shows an error.

I've been using 5.0.0-alpha so didn't notice the problem. Can you try with 5.0.0-alpha-04? That version still has the "old" namespaces so you should be able to use it without changing your code.

**Comment by halcwb** [comment]
Using 5.0.0-alpha-04 indeed resolves the problem. I saw that in another project.
