### ISSUE TITLE
What are the Fable.React 5 replacements for these types?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/fable-react#155]
The following types seem to have been removed in Fable.React 5. What should be used now?

* `CSSProperties`
* `FormEvent`
* `FocusEvent`

**Comment by MangelMaxime** [comment]
[Quoting Announcing fable-compiler 2.2, Fable.Core 3 and more](https://fable.io/blog/Announcing-2-2.html#fable-react) :)

> The React event interfaces have been replaced with Browser.Types. Except for SyntheticEvent and FormEvent (which are just assimilated to Event), the other events have corresponding ones with same name.

I don't know for `CSSProperties`

**Comment by cmeeren** [comment]
Thanks, but `FormEvent` doesn't seem to exist in the `Browser.Types` namespace (or even in this repo). For the record, neither does `CSSProperties`.

**Comment by MangelMaxime** [comment]
If I understand correctly the quotes `SyntheticEvent` and `FormEvent` are now `Event`.

**Comment by cmeeren** [comment]
Oh, sorry, I really need to learn how to read. 😳 Thanks!

Just `CSSproperties` left, then.

**Comment by alfonsogarciacaro** [comment]
Because Fable.React uses union types to represent React props, ideally you should use something [like `Style` to accept a `CSSProp` list](https://github.com/fable-compiler/fable-react/blob/c93fd243b3cfce0cf195929fa423d9641c45b0da/src/Fable.React.Props.fs#L876-L877).

If you need to get a handle of the CSSProperties object, you could use something like this:

```fsharp
type CSSProperties =
    interface end

let inline cssProps (css: CSSProp list): CSSProperties =
    keyValueList CaseRules.LowerFirst css :?> _
```

We're trying to make all helpers in Fable.React compatible with SSR. So it's a bit tricky to add such a function directly to this library.

**Comment by cmeeren** [comment]
Thanks! I'll defer the API decision in this particular context to the maintainer of Fable.MaterialUI, since I haven't been able to figure out how the props using `CSSProperties` are intended to be used.
