### ISSUE TITLE
React is not loaded properly when Fable.React is referenced from a Class Library

### ISSUE THREAD

**Issue by fc1943s** [fable-compiler/fable-react#190]
Project to reproduce: https://github.com/fc1943s/fable-react-compile-error

Steps:
```
cd App
yarn install
yarn run webpack-dev-server
```

I want to keep my Custom Hooks in a separate library, but react is not loaded properly when any code from the Fable.React.HookBindings module is present in a project which is not the main one (loaded from webpack.config.js).
Is this a problem in Fable.React or Fable?

#### Code:

![image](https://user-images.githubusercontent.com/688618/78632522-94bad380-7875-11ea-9318-f138985bb0fd.png)
Note that deleting the `Hooks.useRef` line automatically compiles everything with HMR.
It compiles just fine when moving said line from the "Library" project to the "App" project.

#### Compilation errors:

![image](https://user-images.githubusercontent.com/688618/78632063-64266a00-7874-11ea-9277-926fcf1143f1.png)

![image](https://user-images.githubusercontent.com/688618/78632082-74d6e000-7874-11ea-86cc-246018ef4a08.png)

![image](https://user-images.githubusercontent.com/688618/78632101-81f3cf00-7874-11ea-8c58-4c021499ffa8.png)

**Comment by MangelMaxime** [comment]
The problem is not because you are creating a separate library but because of your project setup and how webpack works.

When webpack is searching for an npm package it will search a `node_modules` folder from the directory with the file requiring it. If it's not found it will look at the parent level etc.

In your case, the `node_modules` are hosted inside the `App` so it can't be found directly by webpack from `Lib` folder.

You have 2 solutions to solve the problem:

Move your `package.json` at the root of your repository.

Or explain to webpack where it can find the `node_modules` folder by using something like:

```js
module.exports = {
  //...
  resolve: {
    modules: ['node_modules', path.resolve(__dirname, "node_modules")]
  }
};
```

[Webpack documentation](https://webpack.js.org/configuration/resolve/#resolvemodules)

**Comment by fc1943s** [comment]
Wonderful! It works. Thank you!
