### ISSUE TITLE
Publish source files from Fable.React.Types and Fable.ReactDom.Types to nuget

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/fable-react#235]
Right now, when libraries depend on `Fable.React.Types` or `Fable.ReactDom.Types`, Femto cannot detect NPM package metadata from these libraries because their sources aren't published to nuget. Any chance you could publish those? 🙏

**Comment by alfonsogarciacaro** [comment]
Ah, I see. Hmm, one of the reasons not to publish the sources is in that case Fable will just load the .dll instead of parsing the .fs files which makes compilation a bit faster. But I understand the problem with femto. Maybe we can just publish a different folder (say `fable_metadata`) so Femto can fallback to this but Fable will keep ignoring the sources?

**Comment by MangelMaxime** [comment]
Adding `fable_metadata` will make authoring Fable packages a bit more confusing for the user because it adds another way of doing it.

If I remember correctly, adding the fs files will only impact the compilation once. If they don't change when in watch mode they are not re-process right?

Also the file don't seems that big so the performance gain is not that much measurable on medium/large project no?

**Comment by Zaid-Ajaj** [comment]
I agree with @MangelMaxime that this makes it more confusing, would rather stay conservative about more changes since Fable v4 already brings lots of them

**Comment by MangelMaxime** [comment]
New versions has been released with the source files included

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @MangelMaxime, published Feliz v2.4.0 🚀 which includes the proper NpmPackage dependency definitions
