### ISSUE TITLE
netstandard2.0 target

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-react#38]
Is it strictly necessary? Are we using any of the netstandard2.0?
I believe we should keep targeting 1.6, while migrating the build itself to SDK 2.0. 
This would lower the requirements for the consumers, which is a good thing.

EDIT: Elmish building with SDK 2.0, targeting netstandard1.6 - https://github.com/fable-elmish/elmish/blob/master/src/Fable.Elmish.fsproj

**Comment by MangelMaxime** [comment]
I think like @et1975 if we can avoid to force user to upgrade their project would be nice. For example, if I make public next version of Fable.Elmish.Bulma all the users would be forced to upgrade their systems and projects.
 Could be better to not force them IMO. As it's kind of breaking change we could avoid no ?

**Comment by MangelMaxime** [comment]
Wait I just think about something. 

With Fable we are sharing the fsproj file which itself target netstandard2.0 so in any case we need the users to update to it no ?

**Comment by et1975** [comment]
Yes, if Fable.Core targets 2.0 we may have to upgrade anyway... and Fable.Core will probably want to target netstandard2.0 for ... TypeProviders? What else is it good for in JS world?
cc @enricosada @ncave @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
My main reason was that netstandard2.0 doesn't have the System.XXX dependencies so I was guessing that moving everything to netstandard2.0 we could alleviate the size of the `packages` folder. However latest Paket version has an option to use Nuget cache instead and I'm working to make Fable able to access library sources even if they're not in the packages folder. If it works, we may not need to upgrade everything to netstandard2.0 at the end :)

**Comment by MangelMaxime** [comment]
Ok, so we would need to update a project to netstandard 2.0 only if it's use a netstandard 2.0 feature ?
Like type providers ?

**Comment by MangelMaxime** [comment]
Even if Fable.Core doesn't target 2.0, if any of the lib used by the user use an fsproj with 2.0 format (no manual FSharp.Net.SDK in it) then will users need to upgrade to netstandard 2.0 ?

I am asking the question because in order to build a library with netstandard 2.0 runtime we need to modify the fsproj (remove FSharp.Net.SDK references, etc.). But when working on a project including both netstandard 2.0 and netstandard 1.6 libs it's compiling. Which is normal as netstandard is orthonogal to 1.6.

However Fable, use internally project reference to include others project files into your application and access the whole AST etc. And it's working even if some of the fsproj are using netstandard 1.6 format. Is it only *the main project* which need to implement the runtime specificities ?

**Comment by alfonsogarciacaro** [comment]
I've released a fable-react 1.2.0-beta-002 targeting netstandard1.6 again :+1: But please note there're still a few breaking API changes (basically you'll have to remove the `!^` wherever the compiler complaints).

**Comment by MangelMaxime** [comment]
I am closing as we released a stable version.
